import websocket
ws = websocket.WebSocket()
ws.connect("ws://api.poloniex.com")
print ("Sending 'Hello, World'...")
ws.send("Hello, World")
print ("Sent")
print ("Receiving...")
result = ws.recv()
print ("Received '%s'" % result)
ws.close()
